defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: felixbellanger

test:
  <<: *defaults
  database: felixbellanger_test

production:
  <<: *defaults
  database: felixbellanger_prod

